npx shadcn@2.3.0 add "https://v0.dev/chat/b/b_TEmHx89y24I?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..4F0JcRMUk5c20sdR.04sbUjUOsu4Ukhf35KelZkY-ZtvC3RziZ6TaGSWr2FRX3TLuCcamRTNmUj4.ffnjcCsOe5Z-X-ulJcB7AQ"
